
src       = gc.c
target    = gc.a
libs      = pthread rt
deps      = robustlock pagepool rbtree array\
            region slab bitmap table str

test_exec = test_gc

BASE_DIR ?= $(CURDIR)/..
include $(BASE_DIR)/def.mk
