
src       = pagepool.c
target    = pagepool.a
test_exec = test_pagepool
deps      = \
	    array \
	    rbtree \
	    region \
	    robustlock \
	    util

libs      = rt pthread

BASE_DIR ?= $(CURDIR)/..
include $(BASE_DIR)/def.mk
