
src       = table.c
target    = table.a
libs      = pthread rt
deps      = robustlock pagepool rbtree\
            array region slab bitmap str gc

test_exec = test_table

BASE_DIR ?= $(CURDIR)/..
include $(BASE_DIR)/def.mk
