
src       = robustlock.c
target    = robustlock.a
libs      = pthread
cflags    = -pthread

deps      = \
	    util \

test_exec = test_robustlock

BASE_DIR ?= $(CURDIR)/..
include $(BASE_DIR)/def.mk
